### ISSUE TITLE
Cant get videos 

### ISSUE THREAD

**Issue by dennispedersenakqa** [limbo-works/Limbo.Umbraco.TwentyThree#4]
Hi Anders and co!

Umbraco version: 13.2
Package version: 13.0.0

When trying to use this and press "Select video" im getting the following error. I also tried to recreate the application in twentythree backend and redo the credentials. 

The logs show this:
`Failed getting list of players from the TwentyThree API: "invalid_oauth_signature" `

The same will appear if I try to select spot.

I do however realise that it might be me not setting it up correctly. So im open to all feedback aswell

Also in logs:
`Skybrud.Social.TwentyThree.Exceptions.TwentyThreeHttpException: Invalid response received from the TwentyThree API (status: 200)
   at Skybrud.Social.TwentyThree.Responses.TwentyThreeResponse.ValidateResponse(IHttpResponse response, JObject& body)
   at Skybrud.Social.TwentyThree.Responses.Players.TwentyThreePlayerListResponse..ctor(IHttpResponse response)
   at Skybrud.Social.TwentyThree.Endpoints.TwentyThreePlayersEndpoint.GetList(TwentyThreeGetPlayersOptions options)
   at Limbo.Umbraco.TwentyThree.Controllers.TwentyThreeController.GetPlayers(Guid credentialsId)`

![image](https://github.com/limbo-works/Limbo.Umbraco.TwentyThree/assets/127423343/8d387af3-1f19-43bd-9878-6bb2583bc2e9)

**Comment by abjerner** [comment]
Hi @dennispedersenakqa 

We haven't encountered this, and but I can think of a few versions for this. One could be an outdated dependency.

Limbo.Umbraco.TwentyThree v13.0.0 has a dependency for Skybrud.Social.TwentyThree v1.1.2, which again has a dependency for Skybrud.Essentials.Http v1.1.0 (which is the package) that handles the OAuth part.

Skybrud.Essentials.Http v1.1.0 is from september 2022, so it's a bit old. The newest version is `v1.2.0`, and it's about a month old. Can you check what version you're using, and if upgrading to the newest version fixes the issue? AFAIK from my release notes, there shouldn't be any changes to the OAuth logic, but might still be worth giving an update a try.

If doesn't help, can you share the structure of the `Limbo` section of your `appsettings.json` file? Please don't share actual secrets here or other sensitive information - it's just so I can see how the package has been configured.

**Comment by dennispedersenakqa** [comment]
Hey @abjerner 

I deeply apologize - I found a space in the end of my secret! Quite emberrasing :D Thanks for making me look at the settings one more time!
